bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 2048
debug: true

num_choices: 1

# OpenAI API key
api_key: ""

# a list of model to generate answers
model_list:
  - gpt-4o-mini
  - gpt-4o
  - o3-mini-2025-01-31
 



# oai like format
gigachat_lite:
    model_name: GigaChat
    endpoints:
        - auth_token: ...
    api_type: gigachat
    parallel: 1

gigachat_pro:
    model_name: GigaChat-Pro
    endpoints:
        - auth_token: ...
    api_type: gigachat
    parallel: 1

best_tgpt_checkpoint:
    model_name: './best_tgpt_checkpoint/'
    endpoints:
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 6


gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints:
        - api_base: https://api.openai.com/v1/
          api_key: ...
    api_type: openai
    parallel: 3

gpt-4o-mini:
    model_name: gpt-4o-mini
    endpoints:
        - api_base: https://api.openai.com/v1/
          api_key: ...
    api_type: openai
    parallel: 6

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints:
        - api_base: https://api.openai.com/v1/
          api_key: ...
    api_type: openai
    parallel: 6

gpt-3.5-turbo-1106:
    model_name: gpt-3.5-turbo-1106
    endpoints:
        - api_base: https://api.openai.com/v1/
          api_key: ...
    api_type: openai
    parallel: 6

gpt-3.5-turbo-0125-ru-sys:
    model_name: gpt-3.5-turbo-0125
    endpoints:
        - api_base: https://api.openai.com/v1/
          api_key: ...
    system_prompt: You are a helpful assistant. Answer on Russian.
    api_type: openai
    parallel: 6